# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c69019ccbd718398f4c63513acfabb97adc882421fced5d6f80a88edf61ab2f02e8addd2e13167c16e3f02f59d11924ff20cba34fcb54214647e82d6dcbe30e3

test:
  secret_key_base: 007832629bcc152619bd9515909ed6888c10ddd2ca17ec54c3448f4fbd8d0e3654262c7c07dcefb80db72d7d03b454aad22495024682cc2e812e3624da8338c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
